AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  portfolio-backend

  Sample SAM Template for portfolio-backend

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Architectures:
      - x86_64
  
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get

  UpdateVisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/update_counter  
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          Table: !Ref VisitorCounterTable
      Policies:
        # Give Create/Read/Update/Delete Permissions to the VisitorCounter
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitorCounterTable
      Events:
        UpdateCounter:
          Type: Api
          Properties:
            Path: /counter
            Method: POST  
      Tags: 
        Key: Project
        Value: cloud-resume-challenge
  VisitorCounterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: 
        Name: visitors
        Type: Number
      TableName: "VisitorCounter"
      Tags: 
        Key: Project
        Value: cloud-resume-challenge
  
  

    
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/counter/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
  UpdateVisitorCounterFunction:
    Description: Update Visitor Counter Function ARN
    Value: !GetAtt UpdateVisitorCounterFunction.Arn
  UpdateVisitorCounterFunctionIamRole:
    Description: Implicit IAM Role created for Update Visitor Counter Function
    Value: !GetAtt UpdateVisitorCounterFunction.Arn
